DROP TABLE IF EXISTS `cpuCooler`;
CREATE TABLE IF NOT EXISTS `cpuCooler` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) DEFAULT NULL,
  `slug` varchar(50) DEFAULT NULL,
  `designer` varchar(50) DEFAULT NULL,
  `price` varchar(50) DEFAULT NULL,
  `description` varchar(50) DEFAULT NULL,
  `component` varchar(50) DEFAULT NULL,
  `sockets` varchar(50) DEFAULT NULL,
  `attachment` varchar(50) DEFAULT NULL,
  `soundlevel` varchar(50) DEFAULT NULL,
  `cpu` varchar(50) DEFAULT NULL,
  `equipment` varchar(50) DEFAULT NULL,
  `ledcolors` varchar(50) DEFAULT NULL,
  `rpm` varchar(50) DEFAULT NULL,
  `material` varchar(50) DEFAULT NULL,
  `heatpipeconnections` varchar(50) DEFAULT NULL,
  `airflow` varchar(50) DEFAULT NULL,
  `staticpressure` varchar(50) DEFAULT NULL,
  `powerconnector` varchar(50) DEFAULT NULL,
  `accessoires` varchar(50) DEFAULT NULL,
  `leds` varchar(50) DEFAULT NULL,
  `bearings` varchar(50) DEFAULT NULL,
  `impeller` varchar(50) DEFAULT NULL,
  `heatpipes` varchar(50) DEFAULT NULL,
  `dimensions` varchar(50) DEFAULT NULL,
  `releasedate` varchar(50) DEFAULT NULL,
  `weight` varchar(50) DEFAULT NULL,
  `information` varchar(50) DEFAULT NULL,
  `warranty` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

INSERT INTO `cpuCooler` (`id`, `name`, `slug`, `designer`, `price`, `description`, `component`, `sockets`, `attachment`, `soundlevel`, `cpu`, `equipment`,
 `ledcolors`, `rpm`, `material`, `heatpipeconnections`, `airflow`, `staticpressure`, `powerconnector`, `accessoires`, `leds`, `bearings`, `impeller`,
  `heatpipes`, `dimensions`, `releasedate`, `weight`, `information`, `warranty`) VALUES
  (1, 'H7 Quad Lumi', '', 'Cryorig', 
  '€69,90', 'Weer een standaard descriptiie', 'CPU Cooler', '1155, AM3+, FM1, 1150, FM2, 1151, 2011-3, AM4', 'Geschroefd',
  '10 dB tot 25 dB', '160 W', 'LED', 'RGB', '330 tot 1600 RPM', 
  'Koper', '4 St.', '83,3 m³/h (49 cfm)', 'Tot 1,65 mm/H2O', '4-Pin PWM', 
  'Montageschroeven, Koelpasta', 'RGB, Logo', 'HPLN (High Precision Low Noise)', '40 Sts., T = 0,4 mm, Gap = 2,2 mm ', '4x 6mm heatpipe ', 
  '123 mm x 145 mm x 98 mm', '01/01/2017', '713 Gram', 'Al weer de standaard onzin', '60 Maanden');