DROP TABLE IF EXISTS `motherboard`;
CREATE TABLE IF NOT EXISTS `motherboard` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) DEFAULT NULL,
  `slug` varchar(50) DEFAULT NULL,
  `designer` varchar(50) DEFAULT NULL,
  `description` varchar(50) DEFAULT NULL,
  `price` varchar(50) DEFAULT NULL,
  `formfactor` varchar(50) DEFAULT NULL,
  `socket` varchar(50) DEFAULT NULL,
  `supportedcpu` varchar(50) DEFAULT NULL,
  `chipset` varchar(50) DEFAULT NULL,
  `pciex1` varchar(50) DEFAULT NULL,
  `pciex16` varchar(50) DEFAULT NULL,
  `uefibios` varchar(50) DEFAULT NULL,
  `use` varchar(50) DEFAULT NULL,
  `power` varchar(50) DEFAULT NULL,
  `maxmemory` varchar(50) DEFAULT NULL,
  `memoryslots` varchar(50) DEFAULT NULL,
  `supportedtype` varchar(50) DEFAULT NULL,
  `supportedstandard` varchar(50) DEFAULT NULL,
  `channels` varchar(50) DEFAULT NULL,
  `memoryranks` varchar(50) DEFAULT NULL,
  `memorycontroller` varchar(50) DEFAULT NULL,
  `maxdatadensity` varchar(50) DEFAULT NULL,
  `keyboard` varchar(50) DEFAULT NULL,
  `mice` varchar(50) DEFAULT NULL,
  `usb3` varchar(50) DEFAULT NULL,
  `usb3c` varchar(50) DEFAULT NULL,
  `usb2` varchar(50) DEFAULT NULL,
  `vga` varchar(50) DEFAULT NULL,
  `dvid` varchar(50) DEFAULT NULL,
  `hdmi` varchar(50) DEFAULT NULL,
  `microphone` varchar(50) DEFAULT NULL,
  `linein` varchar(50) DEFAULT NULL,
  `lineout` varchar(50) DEFAULT NULL,
  `rj45` varchar(50) DEFAULT NULL,
  `m2` varchar(50) DEFAULT NULL,
  `m2key` varchar(50) DEFAULT NULL,
  `m2interface` varchar(50) DEFAULT NULL,
  `m2length` varchar(50) DEFAULT NULL,
  `pwmfan` varchar(50) DEFAULT NULL,
  `satacontroller` varchar(50) DEFAULT NULL,
  `usbcontroller` varchar(50) DEFAULT NULL,
  `sounds` varchar(50) DEFAULT NULL,
  `lan` varchar(50) DEFAULT NULL,
  `features` varchar(50) DEFAULT NULL,
  `releasedate` varchar(50) DEFAULT NULL,
  `information` varchar(50) DEFAULT NULL,
  `warranty` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

INSERT INTO `motherboard` (`id`, `name`, `slug`, `designer`, `description`, `price`, `formfactor`, `socket`, `chipset`,
  `pciex1`, `pciex16`, `uefibios`, `use`, `power`, `maxmemory`, `memoryslots`, `memoryranks`, `memorycontroller`,
  `satacontroller`, `usbcontroller`, `supportedcpu`, `supportedtype`, `supportedstandard`, `channels`, `maxdatadensity`, `keyboard`, `mice`, 
  `usb3`, `usb3c`, `usb2`, `vga`, `dvid`, `hdmi`, `microphone`, `linein`, `lineout`, `rj45`,
  `m2`, `m2key`, `m2interface`, `m2length`, `pwmfan`, `sounds`, `lan`, `features`, `releasedate`, `information`, `warranty`) VALUES
(1, 'B250M PRO-VDH', '', 'MSI', 'Hier is de descriptie van het product', '€74', 'µATX', '1151', 'Intel® B250', 
  '2x', '1x', 'Ja', 'PC', 'EPS (24+8-Pin)', '64 GB', '4x DDR4', '8', 'Ja',
  'Intel® B250 (PCH)', 'Intel® B250', '1x', 'SDRAM-DDR4', 'DDR4 DDR4-2133, DDR4-2400', '2x', '8192', '1x', '1x',
  '3x', '1x', '2x', '1x', '1x', '1x', '1x', '1x', '1x', '1x', 
  '1x', 'M', 'SATA, PCIe', '42 - 80 mm', '3','Realtek ALC887', 'Realtek RTL8111H', 'Windows 7 ready, Windows 8 ready, Windows 10 ready', '01/01/2017', 'Hier is de informatie van het product', '24 Maanden');